consensusnodes:
    node0:
        pk:
            - 4
            - 62
            - 187
            - 64
            - 19
            - 194
            - 210
            - 150
            - 104
            - 104
            - 162
            - 245
            - 93
            - 239
            - 34
            - 66
            - 85
            - 136
            - 179
            - 188
            - 88
            - 67
            - 144
            - 19
            - 191
            - 102
            - 17
            - 148
            - 203
            - 125
            - 94
            - 89
            - 159
            - 146
            - 39
            - 30
            - 65
            - 82
            - 216
            - 184
            - 17
            - 67
            - 217
            - 208
            - 120
            - 185
            - 184
            - 21
            - 129
            - 40
            - 87
            - 170
            - 106
            - 214
            - 149
            - 155
            - 148
            - 98
            - 63
            - 243
            - 139
            - 148
            - 180
            - 251
            - 254
        ip: 0.0.0.0:30000
difficulty: 0
ellipticcurve:
    - 48
    - 89
    - 48
    - 19
    - 6
    - 7
    - 42
    - 134
    - 72
    - 206
    - 61
    - 2
    - 1
    - 6
    - 8
    - 42
    - 134
    - 72
    - 206
    - 61
    - 3
    - 1
    - 7
    - 3
    - 66
    - 0
    - 4
    - 244
    - 137
    - 110
    - 255
    - 170
    - 89
    - 193
    - 23
    - 29
    - 130
    - 97
    - 105
    - 164
    - 61
    - 250
    - 170
    - 30
    - 155
    - 86
    - 97
    - 153
    - 95
    - 2
    - 72
    - 186
    - 58
    - 222
    - 159
    - 78
    - 240
    - 83
    - 116
    - 68
    - 223
    - 171
    - 243
    - 1
    - 123
    - 111
    - 4
    - 2
    - 10
    - 5
    - 60
    - 254
    - 1
    - 149
    - 79
    - 81
    - 1
    - 211
    - 224
    - 135
    - 143
    - 11
    - 244
    - 223
    - 7
    - 177
    - 160
    - 222
    - 38
    - 41
    - 2
previousoutput:
    - 185
    - 77
    - 39
    - 185
    - 147
    - 77
    - 62
    - 8
    - 165
    - 46
    - 82
    - 215
    - 218
    - 125
    - 171
    - 250
    - 196
    - 132
    - 239
    - 227
    - 122
    - 83
    - 128
    - 238
    - 144
    - 136
    - 247
    - 172
    - 226
    - 239
    - 205
    - 233
running: true
tctype: 0
version: v0.10
