consensusnodes:
    node0:
        ip: "0"
        pk: "0"
    node1:
        ip: "0"
        pk: "0"
    node2:
        ip: "0"
        pk: "0"
    node3:
        ip: "0"
        pk: "0"
    node4:
        ip: "0"
        pk: "0"
    node5:
        ip: "0"
        pk: "0"
    node6:
        ip: "0"
        pk: "0"
ellipticcurve:
    - 48
    - 89
    - 48
    - 19
    - 6
    - 7
    - 42
    - 134
    - 72
    - 206
    - 61
    - 2
    - 1
    - 6
    - 8
    - 42
    - 134
    - 72
    - 206
    - 61
    - 3
    - 1
    - 7
    - 3
    - 66
    - 0
    - 4
    - 152
    - 10
    - 221
    - 13
    - 248
    - 189
    - 154
    - 66
    - 222
    - 185
    - 187
    - 35
    - 127
    - 218
    - 10
    - 112
    - 91
    - 158
    - 40
    - 198
    - 239
    - 38
    - 57
    - 173
    - 172
    - 104
    - 90
    - 137
    - 6
    - 123
    - 123
    - 152
    - 246
    - 20
    - 89
    - 57
    - 44
    - 51
    - 204
    - 246
    - 67
    - 64
    - 79
    - 87
    - 80
    - 235
    - 96
    - 209
    - 199
    - 173
    - 21
    - 168
    - 97
    - 145
    - 85
    - 64
    - 245
    - 245
    - 120
    - 33
    - 5
    - 245
    - 34
    - 127
ftype: 0
previousoutput: "0x12324"
running: true
tctype: 0
version: v0.2
vrftype: 0
