consensusnodes:
    node0:
        ip: "0"
        pk: "0"
    node1:
        ip: "0"
        pk: "0"
    node2:
        ip: "0"
        pk: "0"
    node3:
        ip: "0"
        pk: "0"
    node4:
        ip: "0"
        pk: "0"
    node5:
        ip: "0"
        pk: "0"
    node6:
        ip: "0"
        pk: "0"
ellipticcurve:
ftype: 0
previousoutput: "0x12324"
running: false
tctype: 0
version: v0.5
vrftype: 0
difficulty: 0