consensusnodes:
    node_0:
        pk: "0"
        port: "0"
    node_1:
        pk: "0"
        port: "0"
    node_2:
        pk: "0"
        port: "0"
    node_3:
        pk: "0"
        port: "0"
    node_4:
        pk: "0"
        port: "0"
    node_5:
        pk: "0"
        port: "0"
    node_6:
        pk: "0"
        port: "0"
ellipticcurve:
    - 48
    - 89
    - 48
    - 19
    - 6
    - 7
    - 42
    - 134
    - 72
    - 206
    - 61
    - 2
    - 1
    - 6
    - 8
    - 42
    - 134
    - 72
    - 206
    - 61
    - 3
    - 1
    - 7
    - 3
    - 66
    - 0
    - 4
    - 249
    - 102
    - 90
    - 221
    - 212
    - 102
    - 84
    - 94
    - 215
    - 9
    - 246
    - 116
    - 248
    - 94
    - 106
    - 32
    - 6
    - 206
    - 112
    - 53
    - 109
    - 147
    - 28
    - 165
    - 69
    - 151
    - 114
    - 255
    - 188
    - 71
    - 235
    - 62
    - 102
    - 61
    - 14
    - 252
    - 238
    - 48
    - 10
    - 79
    - 161
    - 35
    - 168
    - 101
    - 173
    - 166
    - 109
    - 216
    - 40
    - 5
    - 37
    - 205
    - 69
    - 41
    - 140
    - 204
    - 226
    - 154
    - 175
    - 51
    - 238
    - 147
    - 191
    - 254
ftype: 0
previousoutput: "0x12324"
running: true
tctype: 0
version: v0.1
vrftype: 0
