import numpy as np
import matplotlib.pyplot as plt
import math

xArray = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
data4 = np.loadtxt(open("4time.csv","rb"),delimiter=",")
data7 = np.loadtxt(open("7time.csv","rb"),delimiter=",")
data10 = np.loadtxt(open("10time.csv","rb"),delimiter=",")
data13 = np.loadtxt(open("13time.csv","rb"),delimiter=",")
data16 = np.loadtxt(open("16time.csv","rb"),delimiter=",")
data19 = np.loadtxt(open("19time.csv","rb"),delimiter=",")
data22 = np.loadtxt(open("22time.csv","rb"),delimiter=",")

plt.figure(1)
plt.xlabel('Round')
plt.ylabel('time(s)')
plt.xlim(1, 9)
plt.ylim(20, 40)
plt.plot(xArray, data4, "o")
plt.plot(xArray, data7, "o")
plt.plot(xArray, data10, "o")
plt.plot(xArray, data13, "o")
plt.plot(xArray, data16, "o")
plt.plot(xArray, data19, "o")
plt.plot(xArray, data22, "o")
plt.plot(xArray, data4)
plt.plot(xArray, data7)
plt.plot(xArray, data10)
plt.plot(xArray, data13)
plt.plot(xArray, data16)
plt.plot(xArray, data19)
plt.plot(xArray, data22)
plt.title('title')
plt.legend(('4','7','10','13','16','19','22'))
plt.savefig("consensus.png")

xArray = np.array([1, 2, 3, 4, 5, 6, 7])
data4Mean = np.mean(data4)
data7Mean = np.mean(data7)
data10Mean = np.mean(data10)
data13Mean = np.mean(data13)
data16Mean = np.mean(data16)
data19Mean = np.mean(data19)
data22Mean = np.mean(data22)
dataMean = np.array([data4Mean,data7Mean,data10Mean,data13Mean,data16Mean,data19Mean,data22Mean])

z1 = np.polyfit(xArray, dataMean, 1)
p1 = np.poly1d(z1)
print(z1)
print(p1)

plt.figure(2)
plt.xlabel('Number of Entropy Nodes')
plt.ylabel('Average Time(s)')
# plt.xlim(0, 70)
plt.plot(xArray, dataMean, "o")
plt.plot(xArray, dataMean)
plt.title('title')
plt.savefig("entropyAverage.png")