node0_ip: "0"
node0_pk: "0"
node1_ip: "0"
node1_pk: "0"
node2_ip: "0"
node2_pk: "0"
node3_ip: "0"
node3_pk: "0"
node4_ip: "0"
node4_pk: "0"
node5_ip: "0"
node5_pk: "0"
node6_ip: "0"
node6_pk: "0"
# node7_ip: "0"
# node7_pk: "0"
# node8_ip: "0"
# node8_pk: "0"
# node9_ip: "0"
# node9_pk: "0"
# node10_ip: "0"
# node10_pk: "0"
# node11_ip: "0"
# node11_pk: "0"
# node12_ip: "0"
# node12_pk: "0"
# node13_ip: "0"
# node13_pk: "0"
# node14_ip: "0"
# node14_pk: "0"
# node15_ip: "0"
# node15_pk: "0"
# node16_ip: "0"
# node16_pk: "0"
# node17_ip: "0"
# node17_pk: "0"
# node18_ip: "0"
# node18_pk: "0"
# node19_ip: "0"
# node19_pk: "0"
# node20_ip: "0"
# node20_pk: "0"
# node21_ip: "0"
# node21_pk: "0"
# node22_ip: "0"
# node22_pk: "0"
# node23_ip: "0"
# node23_pk: "0"
# node24_ip: "0"
# node24_pk: "0"
# node25_ip: "0"
# node25_pk: "0"
# node26_ip: "0"
# node26_pk: "0"
# node27_ip: "0"
# node27_pk: "0"
# node28_ip: "0"
# node28_pk: "0"
# node29_ip: "0"
# node29_pk: "0"
# node30_ip: "0"
# node30_pk: "0"
# node31_ip: "0"
# node31_pk: "0"
# node32_ip: "0"
# node32_pk: "0"
# node33_ip: "0"
# node33_pk: "0"
# node34_ip: "0"
# node34_pk: "0"
# node35_ip: "0"
# node35_pk: "0"
# node36_ip: "0"
# node36_pk: "0"
# node37_ip: "0"
# node37_pk: "0"
# node38_ip: "0"
# node38_pk: "0"
# node39_ip: "0"
# node39_pk: "0"
# node40_ip: "0"
# node40_pk: "0"
# node41_ip: "0"
# node41_pk: "0"
# node42_ip: "0"
# node42_pk: "0"
# node43_ip: "0"
# node43_pk: "0"
# node44_ip: "0"
# node44_pk: "0"
# node45_ip: "0"
# node45_pk: "0"
# node46_ip: "0"
# node46_pk: "0"
# node47_ip: "0"
# node47_pk: "0"
# node48_ip: "0"
# node48_pk: "0"
# node49_ip: "0"
# node49_pk: "0"
# node50_ip: "0"
# node50_pk: "0"
# node51_ip: "0"
# node51_pk: "0"
# node52_ip: "0"
# node52_pk: "0"
# node53_ip: "0"
# node53_pk: "0"
# node54_ip: "0"
# node54_pk: "0"
# node55_ip: "0"
# node55_pk: "0"
# node56_ip: "0"
# node56_pk: "0"
# node57_ip: "0"
# node57_pk: "0"
# node58_ip: "0"
# node58_pk: "0"
# node59_ip: "0"
# node59_pk: "0"
# node60_ip: "0"
# node60_pk: "0"
ellipticcurve:
ftype: 0
running: false
tctype: 0
version: v6.0
vrftype: 0
difficulty: 0