node0_ip: "0"
node0_pk: "0"
node1_ip: "0"
node1_pk: "0"
node2_ip: "0"
node2_pk: "0"
node3_ip: "0"
node3_pk: "0"
node4_ip: "0"
node4_pk: "0"
node5_ip: "0"
node5_pk: "0"
node6_ip: "0"
node6_pk: "0"
# node7_ip: "0"
# node7_pk: "0"
# node8_ip: "0"
# node8_pk: "0"
# node9_ip: "0"
# node9_pk: "0"
# node10_ip: "0"
# node10_pk: "0"
# node11_ip: "0"
# node11_pk: "0"
# node12_ip: "0"
# node12_pk: "0"
# node13_ip: "0"
# node13_pk: "0"
# node14_ip: "0"
# node14_pk: "0"
# node15_ip: "0"
# node15_pk: "0"
# node16_ip: "0"
# node16_pk: "0"
# node17_ip: "0"
# node17_pk: "0"
# node18_ip: "0"
# node18_pk: "0"
# node19_ip: "0"
# node19_pk: "0"
# node20_ip: "0"
# node20_pk: "0"
# node21_ip: "0"
# node21_pk: "0"
# node22_ip: "0"
# node22_pk: "0"
# node23_ip: "0"
# node23_pk: "0"
# node24_ip: "0"
# node24_pk: "0"
# node25_ip: "0"
# node25_pk: "0"
# node26_ip: "0"
# node26_pk: "0"
# node27_ip: "0"
# node27_pk: "0"
# node28_ip: "0"
# node28_pk: "0"
# node29_ip: "0"
# node29_pk: "0"
# node30_ip: "0"
# node30_pk: "0"
ellipticcurve:
ftype: 0
running: false
tctype: 0
version: v6.0
vrftype: 0
difficulty: 0